version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    #command: go run cmd/main.go -b 0.0.0.0 #using air so below is needed instead. Air has hot reload :)
    command: air cmd/main.go -b 0.0.0.0