version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    privileged: true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    #command: go run cmd/main.go -b 0.0.0.0 #using air so below is needed instead. Air has hot reload :)
    command: air cmd/main.go -b 0.0.0.0
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.core.somaxconn=4069 #65535 #change it to maybe 4069 or 8192 for 2core 4gb ram
    ulimits:
      nofile:
        soft: 26677
        hard: 46677
    depends_on:
      - db
      - redis

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data/
    ulimits:
      nofile:
        soft: 26677
        hard: 46677

  redis:  
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ulimits:
      nofile:
        soft: 26677
        hard: 46677

volumes:
  postgres-db:
  redis-data:
